const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../../public/static/js/atlas-evidence');
const F=require('../../public/static/js/protein-features');
const crypto=require('node:crypto');
const rows=[{id:1,method:'MS',sample_type:'Brain',ambiguous:'Unambiguous',pmid:'12345678; 23456789',position_in_protein:5},{id:2,method:' ms ',sample_type:'Liver',ambiguous:'Ambiguous',pmid:'12345678',position_in_protein:6},{id:3,method:'',sample_type:'Brain',ambiguous:'',pmid:'',position_in_protein:'5/6'}];
test('intersect independent facets and a strict single position without changing original rows',()=>{
 const before=JSON.stringify(rows);assert.deepEqual(E.filter(rows,{method:'ms',sample:'brain'},5).map(r=>r.id),[1]);assert.equal(E.filter(rows,{method:'ms',sample:'brain',ambiguity:'ambiguous'},5).length,0);assert.equal(E.filter(rows,{method:'unknown'}).length,0);assert.deepEqual(E.filter(rows,{pmid:'23456789'}).map(r=>r.id),[1]);assert.deepEqual(E.filter(rows,{method:E.EMPTY,pmid:E.EMPTY}).map(r=>r.id),[3]);assert.equal(JSON.stringify(rows),before);
});
test('facet counts condition on every other filter and preserve unavailable combinations',()=>{const f=E.facets(rows,{method:'ms',sample:'brain'},5);assert.equal(f.method.find(x=>x.value==='ms').count,1);assert.equal(f.sample.find(x=>x.value==='liver').count,0);assert.equal(E.facets(rows,{method:'absent'}).method.find(item=>item.value==='absent').count,0);});
test('URLs retain accession, fragments and exact filtering scope',()=>{const input='https://oglcnac.org/atlas/detail/?id=P12270&method=MS&sample=BRAIN&site=5#atlas-evidence';const filters=E.fromURL(input);assert.equal(filters.method,'ms');const clear=E.toURL(input,filters,null);assert.equal(clear.searchParams.has('site'),false);assert.equal(clear.searchParams.get('id'),'P12270');assert.equal(clear.hash,'#atlas-evidence');assert.equal(E.coordinate('5/6'),null);assert.equal(E.coordinate('9.5'),null);assert.equal(E.coordinate('9007199254740992'),null);});
test('citations include only available verified metadata and retain missing PMID links',()=>{assert.equal(E.citation({pmid:'12345678'}),'PMID: 12345678. https://pubmed.ncbi.nlm.nih.gov/12345678/');assert.equal(E.citation({status:'verified',pmid:'12345678',authors:['Li Y','Smith A'],title:'A study.',journal:'Journal',date:'2024',volume:'5',issue:'2',pages:'3-5',doi:'10.1234/x'}),'Li Y, Smith A. A study. Journal. 2024; 5(2):3-5. doi: 10.1234/x. PMID: 12345678.');});
test('annotation verification rejects wrong accession, stale hashes, absent isoform mappings and wrong lengths',async()=>{
 const sequence='MST',hash=crypto.createHash('sha256').update(sequence).digest('hex');const item={accession:'P12270',status:'verified',snapshot_length:3,source_length:3,snapshot_sha256:hash,source_sha256:hash};
 assert.equal(await F.verify(item,sequence,'P12270'),'verified');assert.equal(await F.verify(item,sequence,'P12270-2'),'identifier_mismatch');assert.equal(await F.verify(item,'MAS','P12270'),'sequence_mismatch');assert.equal(await F.verify({...item,source_sha256:'bad'},sequence,'P12270'),'sequence_mismatch');assert.equal(await F.verify({...item,status:'isoform_annotations_unavailable'},sequence,'P12270'),'isoform_annotations_unavailable');assert.equal(await F.verify(null,sequence,'P12270'),'unavailable');
});
test('annotation boundaries, overlap and lane assignment do not imply biology at conflicted sites',()=>{
 const items=[{type:'Domain',start:1,end:4},{type:'Domain',start:3,end:6},{type:'Region',start:7,end:8},{type:'Region',start:0,end:5},{type:'Repeat',start:9,end:11}];const valid=F.features({features:items},10);assert.equal(valid.length,3);assert.equal(F.lanes(valid)[0].lanes,2);assert.equal(F.overlap(valid,{position:3,site:{mapped:true,mismatch:false}}).length,2);assert.equal(F.overlap(valid,{position:3,site:{mapped:true,mismatch:true}}).length,0);assert.equal(F.overlap(valid,{position:30,site:{mapped:false}}).length,0);
});
