const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http'),playwright=require('playwright'),Papa=require('papaparse');
const {AxeBuilder}=require('@axe-core/playwright');const T=require('../../public/static/js/atlas-tools');
const ROOT=path.resolve(__dirname,'../..'),STATIC=process.env.SITE_STATIC_ROOT||path.join(ROOT,'dist'),MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'};
let browser,server,base,source,papers,contexts=[],errors=[];
test.before(async()=>{source=JSON.parse(await fs.readFile(path.join(ROOT,'public/static/data/atlas-records.json')));papers=JSON.parse(await fs.readFile(path.join(ROOT,'public/static/data/atlas-enrichment/publications.json'))).publications;server=http.createServer(async(req,res)=>{let file=path.join(STATIC,decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!path.extname(file))file=path.join(file,'index.html');try{res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream'}).end(await fs.readFile(file));}catch(_){res.writeHead(404).end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=process.env.SITE_BASE_URL||`http://127.0.0.1:${server.address().port}`;browser=await playwright[process.env.SITE_BROWSER||'chromium'].launch({headless:true});});
test.afterEach(async()=>{await Promise.all(contexts.map(c=>c.close()));contexts=[];const found=errors;errors=[];assert.deepEqual(found,[]);});
test.after(async()=>{await browser?.close();await new Promise(resolve=>server.close(resolve));});
async function page(width=1440){const context=await browser.newContext({viewport:{width,height:1000},acceptDownloads:true});contexts.push(context);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedText=text;}}});});return page;}
async function search(page,url='?q=P12270&field=accession'){await page.goto(base+'/atlas/search/'+url);await page.waitForFunction(()=>window.OglcnacTables?.get('atlas_proteins')&&!OglcnacTables.get('atlas_proteins').loading&&!document.getElementById('atlas-selection-bar').hidden);}
async function count(page,wanted){await page.waitForFunction(n=>OglcnacTables.get('search_result').totalRows===n,wanted);}
async function download(page,selector){const pending=page.waitForEvent('download');await page.locator(selector).click();const item=await pending;return {name:item.suggestedFilename(),text:await fs.readFile(await item.path(),'utf8')};}
async function review(page,id='A0A0C4DFX4',position=2416){await page.goto(base+`/atlas/review/?id=${id}&site=${position}`);await page.waitForFunction(()=>!document.getElementById('review-save').disabled);}
async function compare(page,ids='P12270,P18583,O15294'){await page.goto(base+'/atlas/compare/?ids='+ids);await page.waitForSelector('#comparison-grid[data-ready=true]');}
const fixtureCollection=()=>({kind:'oglcnac-collections',schema_version:1,collections:[{id:'fixture',name:'Nuclear proteins',accessions:['P12270','P18583','O15294'],updated:'2026-09-30T12:00:00Z'}]});
async function importJSON(page,selector,payload){await page.locator(selector).setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});}

test('context filters, conditional counts, source export, history and detail year scope agree',async()=>{
 const p=await page();await search(p);const rows=source.filter(r=>r.accession==='P12270'),row=rows.find(r=>T.pmids(r).some(id=>papers[id]?.year));const year=String(papers[T.pmids(row)[0]].year),filters={species:T.normalize(row.species),method:T.normalize(row.method),sample:T.normalize(row.sample_type),ambiguity:T.normalize(row.ambiguous),pmid:T.pmids(row)[0],year};
 for(const [key,value]of Object.entries(filters))await p.selectOption('#atlas-'+key+'-filter',value);
 const expected=T.filter(rows,filters,papers);assert.ok(expected.length);await count(p,expected.length);
 const csv=Papa.parse((await download(p,'#atlas-download-matching')).text,{header:true,skipEmptyLines:true});assert.deepEqual(csv.data.map(r=>Number(r.id)),expected.map(r=>r.id));assert.deepEqual(new Set(csv.meta.fields),new Set(Object.keys(rows[0])));
 const link=await p.locator('#atlas_proteins tbody a').first().getAttribute('href');assert.equal(new URL(link,base).searchParams.get('year'),year);
 await p.locator('#atlas-clear-filters').click();await count(p,rows.length);await p.goBack();await count(p,expected.length);await p.reload();await count(p,expected.length);
 await p.goto(base+link);await p.waitForSelector('#atlas-feature-viewer[data-state]');await p.waitForFunction(n=>OglcnacTables.get('detail2').totalRows===n,expected.length);assert.equal(await p.locator('#atlas-filter-year').inputValue(),year);
});
test('unknown filters and missing publication metadata never silently broaden search',async()=>{
 const p=await page();await search(p,'?q=P12270&field=accession&method=unknown');await count(p,0);assert.match(await p.locator('#atlas-method-filter').textContent(),/Not in results: unknown/);assert.equal(await p.locator('#atlas-download-matching').isDisabled(),true);
 await p.route('**/atlas-enrichment/publications.json*',r=>r.abort());await search(p,'?q=P12270&field=accession&year=2020');await count(p,0);assert.match(await p.locator('#atlas-search-status').innerText(),/unavailable/);assert.equal(new URL(p.url()).searchParams.get('year'),'2020');await p.unrouteAll();await p.locator('#atlas-search-form button').click();await count(p,75);
});
test('batch paste, upload, exact isoforms and diagnostic CSV are consistent',async()=>{
 const p=await page();await p.goto(base+'/atlas/search/');await p.locator('#atlas-batch summary').click();await p.fill('#atlas-batch-input','P12270, p12270; P12270-99 O15294 <bad>');await p.locator('#atlas-batch-form button').click();await count(p,80);assert.match(await p.locator('#atlas-batch-summary').innerText(),/2 matched · 1 unmatched · 1 duplicate · 1 invalid/);
 await p.locator('#atlas-batch-report > summary').click();const report=Papa.parse((await download(p,'#atlas-download-batch')).text,{header:true,skipEmptyLines:true});assert.deepEqual(report.data.map(r=>r.Result),['matched','duplicate','unmatched','matched','invalid']);
 await p.locator('#atlas-batch-file').setInputFiles({name:'ids.csv',mimeType:'text/csv',buffer:Buffer.from('accession\nP18583\nP12270')});await p.waitForFunction(()=>document.getElementById('atlas-batch-input').value.includes('accession'));await p.locator('#atlas-batch-form button').click();await count(p,179);await p.reload();await count(p,179);
 await p.fill('#atlas-batch-input',Array(501).fill('P12270').join('\n'));await p.locator('#atlas-batch-form button').click();assert.match(await p.locator('#atlas-search-status').innerText(),/no entries were processed/);await count(p,179);
});
test('collections save selected proteins across filters, append from records and survive reload with backup parity',async()=>{
 const p=await page();await search(p,'?ids=P12270,P18583,O15294');await p.locator('#atlas_proteins input').first().focus();await p.keyboard.press('Space');assert.match(await p.locator('#atlas-selected-count').innerText(),/^1 selected/);await p.locator('#atlas-select-matching').click();await p.locator('.atlas-save-disclosure summary').click();await p.getByLabel('New collection name',{exact:true}).fill('Nuclear proteins');await p.locator('#atlas-save-selection button').click();assert.match(await p.locator('#atlas-save-selection [role=status]').innerText(),/Saved 3/);
 await p.goto(base+'/atlas/collections/');await p.waitForFunction(()=>OglcnacTables.get('collection_table').totalRows===3);await p.reload();await p.waitForFunction(()=>OglcnacTables.get('collection_table').totalRows===3);const backup=JSON.parse((await download(p,'#collections-export')).text);assert.deepEqual(new Set(backup.collections[0].accessions),new Set(['P12270','P18583','O15294']));
 await p.locator('#collection-select-all').click();assert.equal(await p.locator('#collection-compare').isDisabled(),false);await p.locator('#collection-remove').click();await p.waitForFunction(()=>OglcnacTables.get('collection_table').totalRows===0);await p.locator('#collection-undo').click();await p.waitForFunction(()=>OglcnacTables.get('collection_table').totalRows===3);
 await p.goto(base+'/atlas/detail/?id=P49792');await p.waitForSelector('#atlas-record-actions:not([hidden])');await p.locator('#atlas-record-actions summary').click();await p.getByLabel('Save to collection',{exact:true}).selectOption(backup.collections[0].id);await p.locator('#atlas-detail-save button').click();assert.match(await p.locator('#atlas-detail-save [role=status]').innerText(),/Saved 1/);
 await p.goto(base+'/atlas/collections/');await p.waitForFunction(()=>OglcnacTables.get('collection_table').totalRows===4);await importJSON(p,'#collections-import',backup);await p.waitForFunction(()=>document.getElementById('collections-status').textContent.includes('Backup restored'));assert.equal(await p.locator('#collection-list button').count(),2);
});
test('collection restore is atomic, missing entries are explicit, deletion can be cancelled and undone',async()=>{
 const p=await page();await p.goto(base+'/atlas/collections/');const data=fixtureCollection();data.collections[0].accessions.push('MISSING');await importJSON(p,'#collections-import',data);await p.waitForFunction(()=>OglcnacTables.get('collection_table').totalRows===4);assert.match(await p.locator('#collection_table').innerText(),/Not found in this Atlas release/);
 const invalid=fixtureCollection();invalid.collections[0].accessions.push('<bad>');await importJSON(p,'#collections-import',invalid);await p.waitForFunction(()=>document.getElementById('collections-status').textContent.includes('invalid'));assert.equal(await p.locator('#collection-list button').count(),1);
 await p.locator('#collection-delete').click();await p.locator('#collection-delete-cancel').click();assert.equal(await p.locator('#collection-list button').count(),1);await p.locator('#collection-delete').click();await p.locator('#collection-delete-confirm').click();assert.equal(await p.locator('#collection-list button').count(),0);await p.locator('#collection-undo').click();await p.waitForFunction(()=>OglcnacTables.get('collection_table').totalRows===4);
});
test('blocked local storage is reported without falsely saving a collection',async()=>{
 const p=await page();await p.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('Quota exceeded');};});await search(p,'?ids=P12270,O15294');await p.locator('#atlas-select-matching').click();await p.locator('.atlas-save-disclosure summary').click();await p.getByLabel('New collection name',{exact:true}).fill('Blocked');await p.locator('#atlas-save-selection button').click();assert.match(await p.locator('#atlas-save-selection [role=status]').innerText(),/Could not save/);assert.equal(await p.evaluate(()=>localStorage.getItem('oglcnac:collections:v1')),null);
});
test('comparison includes complete evidence, independent sequence axes, verified annotations and portable summaries',async()=>{
 const p=await page();await compare(p);assert.equal(await p.locator('.atlas-comparison-protein').count(),3);assert.equal(await p.locator('.atlas-comparison-track').count(),3);assert.match(await p.locator('#compare-note').innerText(),/not aligned/);const csv=Papa.parse((await download(p,'#compare-export')).text,{header:true,skipEmptyLines:true});for(const row of csv.data){assert.equal(Number(row.evidence_records),source.filter(r=>r.accession===row.accession).length);assert.equal(row.annotation_state,'verified');assert.equal(row.coordinates,'Independent; not aligned');}
 await p.locator('#compare-share').click();assert.equal(await p.evaluate(()=>window.copiedText),p.url());await p.locator('.atlas-comparison-protein').first().getByText('Reported positions (27)',{exact:true}).click();assert.ok(await p.locator('.atlas-coordinate-list a').count()>0);
 await p.fill('#compare-ids','P12270,P18583,O15294,P49792');await p.locator('#compare-form button').click();await p.waitForFunction(()=>document.querySelectorAll('.atlas-comparison-protein').length===4);assert.match(await p.locator('[data-accession=P49792]').innerText(),/residue conflict/);
 await p.fill('#compare-ids','P12270,P12270');await p.locator('#compare-form button').click();assert.match(await p.locator('#compare-status').innerText(),/distinct/);
});
test('comparison handles missing entries, absent sequences and incompatible provider metadata conservatively',async()=>{
 const p=await page();await p.route('**/atlas-enrichment/proteins/*.json*',async r=>{const response=await r.fetch();const payload=await response.json();if(payload.proteins.P12270)payload.proteins.P12270.source_sha256='wrong';await r.fulfill({response,json:payload});});await compare(p,'P12270,Q6UN15-1,MISSING');assert.match(await p.locator('[data-accession=P12270]').innerText(),/Verified annotation coordinates are unavailable/);assert.match(await p.locator('[data-accession="Q6UN15-1"]').innerText(),/No local sequence/);assert.match(await p.locator('[data-accession=MISSING]').innerText(),/No exact Atlas record/);
});
test('curator queue covers all conflicts; decisions append, restore and never change source coordinates',async()=>{
 const p=await page();await review(p);assert.equal(await p.evaluate(()=>OglcnacTables.get('review_table').totalRows),1046);assert.match(await p.locator('#review-case-context').innerText(),/2239/);await p.fill('#reviewer-name','Example curator');await p.fill('#review-rationale','The supplementary peptide needs manual verification.');await p.locator('#review-save').click();assert.match(await p.locator('#review-save-status').innerText(),/Published Atlas evidence is unchanged/);
 await p.selectOption('#review-decision-value','propose-correction');await p.fill('#review-coordinate','2239');await p.fill('#review-rationale','Example proposal for testing the local review history.');await p.fill('#review-pmids','12345678');await p.locator('#review-save').click();assert.equal(await p.locator('#review-history>li').count(),2);assert.match(await p.locator('#review-case-title').innerText(),/2416/);const backup=JSON.parse((await download(p,'#review-export')).text);assert.equal(backup.events.length,2);
 await p.reload();await p.waitForFunction(()=>!document.getElementById('review-save').disabled);assert.equal(await p.locator('#review-history>li').count(),2);await p.locator('#review-queue > summary').click();await p.selectOption('#review-progress','propose-correction');assert.equal(await p.evaluate(()=>OglcnacTables.get('review_table').totalRows),1);
 const other=await page();await review(other);await importJSON(other,'#review-import',backup);await other.waitForFunction(()=>document.querySelectorAll('#review-history>li').length===2);await importJSON(other,'#review-import',backup);await other.waitForFunction(()=>document.getElementById('review-status').textContent.includes('restored'));assert.equal(await other.locator('#review-history>li').count(),2);
 backup.events[0].rationale='This attempts to change an existing decision.';await importJSON(other,'#review-import',backup);await other.waitForFunction(()=>document.getElementById('review-status').textContent.includes('Conflicting'));assert.equal(await other.locator('#review-history>li').count(),2);
});
test('audit load failure has a working retry and direct case links reject unknown positions',async()=>{
 const p=await page();await p.route('**/mapping-audit.json*',r=>r.abort());await p.goto(base+'/atlas/review/');await p.waitForSelector('#review-retry:not([hidden])');await p.unrouteAll();await p.locator('#review-retry').click();await p.waitForFunction(()=>OglcnacTables.get('review_table').totalRows===1046);await p.goto(base+'/atlas/review/?id=P12270&site=999999');await p.waitForFunction(()=>document.getElementById('review-status').textContent.includes('not in this mismatch audit'));assert.equal(await p.locator('#review-case').isVisible(),false);
});
for(const width of [1440,390])for(const state of ['search','collections','compare','review'])test(`${state} workflow passes WCAG A/AA without page overflow at ${width}px`,async()=>{
 const p=await page(width);if(state==='search'){await search(p,'?ids=P12270,P18583,O15294,P12270,MISSING');await p.locator('#atlas-batch-report > summary').click();await p.locator('#atlas-select-matching').click();await p.locator('.atlas-save-disclosure summary').click();if(width<901)await p.locator('#atlas-filter-disclosure summary').click();}else if(state==='compare')await compare(p);else if(state==='review')await review(p);else{await p.goto(base+'/atlas/collections/');await importJSON(p,'#collections-import',fixtureCollection());await p.waitForFunction(()=>OglcnacTables.get('collection_table').totalRows===3);}
 const results=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();assert.deepEqual(results.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
});

test('mobile collections retain usable checkboxes and synchronize Select all / Clear selection',async()=>{const p=await page(390);await p.goto(base+'/atlas/collections/');await importJSON(p,'#collections-import',fixtureCollection());await p.waitForFunction(()=>OglcnacTables.get('collection_table').totalRows===3);const checks=p.locator('.native-record-cards input[type=checkbox]');assert.equal(await checks.count(),3);await checks.first().check();assert.match(await p.locator('#collection-selection').innerText(),/^1 selected/);await p.locator('#collection-select-all').click();assert.equal(await checks.evaluateAll(inputs=>inputs.filter(n=>n.checked).length),3);await p.locator('#collection-clear').click();assert.equal(await checks.evaluateAll(inputs=>inputs.filter(n=>n.checked).length),0);});
test('legacy mixed-case accessions resolve exactly in comparison',async()=>{const p=await page();await compare(p,'P12270,LOC_OS01G20110.1');assert.match(await p.locator('#compare-status').innerText(),/2 of 2/);assert.equal(await p.locator('[data-accession="LOC_Os01g20110.1"]').count(),1);});
test('latest imported curator decision follows absolute time across time-zone offsets',async()=>{const p=await page();await review(p);const auditRevision=await p.evaluate(()=>document.getElementById('review-status').textContent.match(/Audit (\w+)/)[1]);const common={key:'A0A0C4DFX4:2416',reviewer:'Example curator',rationale:'Imported review with an explicit timezone.',pmids:[],proposed_position:null};await importJSON(p,'#review-import',{kind:'oglcnac-reviews',schema_version:1,audit_revision:auditRevision,events:[{...common,id:'newer',created:'2026-09-30T10:00:00Z',decision:'retain-source'},{...common,id:'older',created:'2026-09-30T12:00:00+04:00',decision:'needs-evidence'}]});await p.waitForFunction(()=>document.getElementById('review-status').textContent.includes('restored'));assert.match(await p.locator('#review-history>li').first().innerText(),/Retain source value/);await p.locator('#review-queue > summary').click();await p.selectOption('#review-progress','retain-source');assert.equal(await p.evaluate(()=>OglcnacTables.get('review_table').totalRows),1);});
