const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const R=require('../../public/static/js/research-workflows'),F=require('../../public/static/js/protein-figure'),V=require('../../public/static/js/protein-viewer'),P=require('../../public/static/js/protein-features');
const root=path.resolve(__dirname,'../..'),read=name=>JSON.parse(fs.readFileSync(path.join(root,'public/static/data',name)));
const source=read('atlas-records.json'),catalog=read('atlas-research/proteins.json').proteins,studies=read('atlas-research/studies.json').studies,snapshot=read('atlas-sequences-v1.json');
test('every suggestion retains exact source accessions, names, genes and species',()=>{
 const map=new Map();for(const row of source){if(!row.accession)continue;if(!map.has(row.accession))map.set(row.accession,[]);map.get(row.accession).push(row);}assert.equal(catalog.length,map.size);
 for(const item of catalog){const rows=map.get(item.accession);assert.ok(rows);for(const [key,field]of [['names','protein_name'],['genes','gene_name'],['species','species']])assert.deepEqual(item[key],[...new Set(rows.map(r=>String(r[field]||'').trim()).filter(Boolean))].sort());}
});
test('every study count independently agrees with the full original source corpus',()=>{
 const indexed=new Map();for(const row of source)for(const id of new Set(String(row.pmid||'').match(/\b\d{6,9}\b/g)||[])){if(!indexed.has(id))indexed.set(id,[]);indexed.get(id).push(row);}assert.equal(studies.length,indexed.size);
 for(const study of studies){const rows=indexed.get(study.pmid),positions=new Set(rows.filter(r=>r.accession&&/^\d+$/.test(String(r.position_in_protein||'').trim())&&Number(r.position_in_protein)>0).map(r=>JSON.stringify([r.accession,r.species,Number(r.position_in_protein)])));assert.equal(study.records,rows.length);assert.equal(study.proteins,new Set(rows.map(r=>r.accession).filter(Boolean)).size);assert.equal(study.positions,positions.size);assert.equal(R.studyRows(source,study.pmid).length,rows.length);}
});
test('provenance hashes identify the unchanged full scientific sources',()=>{const manifest=read('atlas-research/manifest.json');for(const name of ['atlas-records.json','atlas-sequences-v1.json','ogt-pin-records.json']){const bytes=fs.readFileSync(path.join(root,'public/static/data',name));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),manifest.sources[name].sha256);}assert.equal(manifest.sources['atlas-records.json'].sha256,'8afafee735320904d2069a88384341c826111ee5ad96dc49134c52ce572b0d65');});
test('suggestions rank exact accession and reported genes, preserve multiple organisms and cap results',()=>{const proteins=[{accession:'P00001',genes:['OGT ALT'],names:['Transferase'],species:['human']},{accession:'Q00001',genes:['OGT'],names:['Transferase'],species:['mouse']},{accession:'OGTLIKE',genes:['OGT2'],names:['Related protein'],species:['human']}];assert.equal(R.suggestions(proteins,'p00001')[0].score,0);const genes=R.suggestions(proteins,'OGT');assert.deepEqual(genes.slice(0,2).map(r=>r.species[0]),['human','mouse']);assert.equal(R.suggestions(proteins,'ogt',1).length,1);assert.equal(R.suggestions(proteins,'absent').length,0);assert.equal(R.suggestions(catalog,'P12270')[0].accession,'P12270');});
test('preparation isolates supported species and never substitutes an absent isoform',()=>{
 const records=[{accession:'P00001',species:'human'},{accession:'Q00001',species:'mouse'},{accession:'RAT',species:'rat'},{accession:'MIX',species:'human'},{accession:'MIX',species:'mouse'},{accession:'BAD',species:'mouse'}];
 const plan=R.preparation(['P00001','Q00001','RAT','MIX','BAD','P00001-2'],records,{sequences:{P00001:'MAST',Q00001:'MST',RAT:'AST',MIX:'MST',BAD:'MUST'}});
 assert.deepEqual(plan.map(r=>r.status),['Ready','Ready','No model for this species','Species is missing or ambiguous','Sequence contains residues unsupported by this model','No exact Atlas record']);assert.equal(R.prepareFasta(plan,'human').included.length,1);assert.match(R.prepareFasta(plan,'mouse').text,/Q00001/);assert.doesNotMatch(R.prepareFasta(plan,'mouse').text,/P00001/);
});
test('actual Atlas sequence preparation preserves source bytes and reports missing sequences',()=>{const plan=R.preparation(['P12270','Q6UN15-1','MISSING'],source,snapshot);assert.equal(plan[0].sequence,snapshot.sequences.P12270);assert.equal(plan[1].status,'No exact sequence in the local snapshot');assert.equal(plan[2].status,'No exact Atlas record');});
test('oversized preparation rejects the complete group without truncation',()=>{assert.throws(()=>R.prepareFasta([{accession:'P1',species:'human',status:'Ready',sequence:'S'.repeat(110000)},{accession:'P2',species:'human',status:'Ready',sequence:'S'.repeat(110000)}],'human'),/no partial group/);});
test('multi-PMID rows belong to both studies and unreported coordinates are excluded from site counts',()=>{const rows=[{id:1,accession:'X',species:'human',position_in_protein:'4',pmid:'12345678; 23456789'},{id:2,accession:'X',species:'human',position_in_protein:'4',pmid:'12345678'},{id:3,accession:'',species:'human',position_in_protein:'4',pmid:'12345678'},{id:4,accession:'X',species:'human',position_in_protein:'unknown',pmid:'12345678'}];assert.deepEqual(R.studySummary(R.studyRows(rows,'12345678')),{records:4,proteins:1,positions:1,missing_accessions:1});assert.equal(R.studyRows(rows,'23456789').length,1);});
const figureOptions=()=>({accession:'P00001',name:'Protein <script>&"',species:'human',sequence:'MASTST',records:[{id:1,position_in_protein:'3',site_residue:'S',ambiguous:'unambiguous',pmid:'12345678'},{id:2,position_in_protein:'4',site_residue:'S',ambiguous:'ambiguous',pmid:'23456789'},{id:3,position_in_protein:'99'},{id:4,position_in_protein:''}],annotation:{state:'verified',metadata:{features:[{type:'Domain',start:2,end:5,description:'Domain <A>'}]}},start:2,end:5});
test('figure preserves source coordinates, residue conflicts, domain ranges and omitted records',()=>{const figure=F.build(figureOptions(),V,P);assert.equal(figure.metadata.sites.length,2);assert.equal(figure.metadata.sites.find(s=>s.position===4).conflict,true);assert.match(figure.svg,/data-position="4" data-kind="conflict"/);assert.match(figure.svg,/data-feature-start="2" data-feature-end="5"/);assert.match(figure.svg,/1 records without a numeric position; 1 records outside/);assert.ok(figure.svg.includes('&lt;script&gt;&amp;&quot;'));assert.ok(!figure.svg.includes('<script>'));});
test('figure rejects invalid ranges and never displays incompatible annotations',()=>{for(const [start,end]of [[0,4],[4,2],[1,7],[1.5,4]])assert.throws(()=>F.build({...figureOptions(),start,end},V,P),/valid region/);const figure=F.build({...figureOptions(),annotation:{state:'sequence_mismatch',metadata:figureOptions().annotation.metadata}},V,P);assert.equal(figure.metadata.annotations.length,0);assert.doesNotMatch(figure.svg,/data-feature-start/);assert.match(figure.svg,/Domain coordinates omitted: sequence_mismatch/);});
test('report ZIP opens with Python zipfile and every content checksum agrees',async()=>{const blob=await R.report({kind:'test',metadata:{scope:'all'},files:{'data.csv':'id,value\n1,"α,β"','input.fasta':'>P1\nMAST\n'}}),bytes=Buffer.from(await blob.arrayBuffer());const {spawnSync}=require('node:child_process');const code='import sys,zipfile,io,json,hashlib\nz=zipfile.ZipFile(io.BytesIO(sys.stdin.buffer.read()))\nassert z.testzip() is None\nm=json.loads(z.read("manifest.json"))\nfor n,v in m["files"].items():\n b=z.read(n);assert hashlib.sha256(b).hexdigest()==v["sha256"];assert len(b)==v["bytes"]\nassert z.read("data.csv").decode()==\'id,value\\n1,"α,β"\'\nprint(len(z.namelist()))';const result=spawnSync('python3',['-c',code],{input:bytes});assert.equal(result.status,0,result.stderr.toString());assert.equal(result.stdout.toString().trim(),'4');});
