#!/usr/bin/env python3
"""Build the complete static site from dependency-free tracked sources."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Dict, Iterable, List, Mapping


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_ROOT = REPOSITORY_ROOT / "site"
DEFAULT_PUBLIC_ROOT = REPOSITORY_ROOT / "public"
DEFAULT_OUTPUT_ROOT = REPOSITORY_ROOT / "dist"
CANONICAL_ORIGIN = "https://oglcnac.org"
ASSET_MANIFEST_OUTPUT = "static/.site-build-assets.json"
ASSET_MANIFEST_OWNER = "scripts/build_site.py"
GENERATED_OWNERSHIP_MARKERS = {
    ".html": b"<!-- Generated by scripts/build_site.py; edit site/ instead. -->",
    ".css": b"/* Generated by scripts/build_site.py; edit site/styles instead. */",
}


class BuildError(Exception):
    """A source configuration or rendering error."""


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise BuildError(f"Cannot read {path}: {error}") from error


def replace_tokens(template: str, values: Mapping[str, str], name: str) -> str:
    rendered = template
    for token, value in values.items():
        rendered = rendered.replace("{{" + token + "}}", value)
    remaining = sorted(set(part.split("}}", 1)[0] for part in rendered.split("{{")[1:]))
    if remaining:
        raise BuildError(f"{name} has unresolved template tokens: {', '.join(remaining)}")
    return rendered


def normalized_route(route: str) -> str:
    if not route.startswith("/"):
        raise BuildError(f"Public route must start with '/': {route}")
    if route == "/":
        return route
    return route.rstrip("/") + "/"


def render_link(
    label: str,
    href: str,
    *,
    current_page: bool = False,
    current_section: bool = False,
) -> str:
    attributes: List[str] = [f'href="{html.escape(href, quote=True)}"']
    if current_page:
        attributes.append('aria-current="page"')
    if current_section:
        attributes.append('data-section-current="true"')
    return (
        f"<li><a {' '.join(attributes)}>"
        f"{html.escape(label, quote=False)}</a></li>"
    )


def render_header(
    page: Mapping[str, object],
    configuration: Mapping[str, object],
    header_template: str,
) -> str:
    route = normalized_route(str(page["route"]))
    section = str(page["section"])
    primary_links = []
    for entry in configuration["primary_navigation"]:
        label, href, link_section = entry
        primary_links.append(
            render_link(
                str(label),
                str(href),
                current_page=route == normalized_route(str(href)),
                current_section=section == str(link_section),
            )
        )

    section_entries = configuration["sections"][section]
    section_navigation = ""
    if section_entries:
        links = [
            render_link(
                str(label),
                str(href),
                current_page=route == normalized_route(str(href)),
            )
            for label, href in section_entries
        ]
        section_navigation = (
            '        <nav class="site-section-nav" aria-label="Section navigation">\n'
            f"          <ul>{''.join(links)}</ul>\n"
            "        </nav>"
        )

    return replace_tokens(
        header_template,
        {
            "HOME_CURRENT": ' aria-current="page"' if route == "/" else "",
            "PRIMARY_LINKS": "".join(primary_links),
            "WORKBENCH_CURRENT": ' aria-current="page"' if route == "/analysis/" else "",
            "SECTION_NAV": section_navigation,
        },
        "header.html",
    )


def load_configuration(source_root: Path) -> Dict[str, object]:
    config_path = source_root / "site.json"
    try:
        configuration = json.loads(read_text(config_path))
    except json.JSONDecodeError as error:
        raise BuildError(f"Invalid JSON in {config_path}: {error}") from error

    required_keys = {"styles", "primary_navigation", "sections", "pages"}
    missing = required_keys.difference(configuration)
    if missing:
        raise BuildError(f"site.json is missing: {', '.join(sorted(missing))}")

    pages = configuration["pages"]
    outputs = [str(page["output"]) for page in pages]
    routes = [normalized_route(str(page["route"])) for page in pages]
    if len(outputs) != len(set(outputs)):
        raise BuildError("site.json contains duplicate generated outputs")
    if len(routes) != len(set(routes)):
        raise BuildError("site.json contains duplicate public routes")
    for page in pages:
        if page["section"] not in configuration["sections"]:
            raise BuildError(
                f"{page['output']} uses unknown section {page['section']}"
            )
    return configuration


def render_page(
    page: Mapping[str, object],
    configuration: Mapping[str, object],
    source_root: Path,
    templates: Mapping[str, str],
) -> str:
    output = str(page["output"])
    source_stem = output[:-5]
    content = read_text(source_root / "pages" / f"{source_stem}.content.html")
    # Source fragments are normal text files with a final line terminator. The
    # terminator belongs to the source file, not to the preserved <main> bytes.
    if content.endswith("\n"):
        content = content[:-1]
    after_path = source_root / "pages" / f"{source_stem}.after.html"
    after_content = read_text(after_path) if after_path.exists() else ""
    head_scripts = "\n".join(
        f'  <script defer src="{html.escape(str(source), quote=True)}"></script>'
        for source in page.get("head_scripts", [])
    )
    head_markup = str(page.get("head_markup", ""))
    route = normalized_route(str(page["route"]))
    canonical_url = CANONICAL_ORIGIN + (route if route != "/" else "/")

    return replace_tokens(
        templates["layout"],
        {
            "TITLE": html.escape(str(page["title"]), quote=False),
            "DESCRIPTION": html.escape(str(page["description"]), quote=True),
            "CANONICAL_URL": html.escape(canonical_url, quote=True),
            "HEAD_MARKUP": head_markup,
            "HEAD_SCRIPTS": head_scripts,
            "BODY_CLASS": html.escape(str(page["body_class"]), quote=True),
            "HEADER": render_header(page, configuration, templates["header"]),
            "MAIN_CLASS": html.escape(str(page["main_class"]), quote=True),
            "CONTENT": content,
            "FOOTER": templates["footer"],
            "AFTER_CONTENT": after_content,
        },
        output,
    )


def generated_files(source_root: Path, public_root: Path) -> Dict[str, bytes]:
    if not public_root.is_dir():
        raise BuildError(f"Public source directory does not exist: {public_root}")
    configuration = load_configuration(source_root)
    template_root = source_root / "templates"
    templates = {
        "layout": read_text(template_root / "layout.html"),
        "header": read_text(template_root / "header.html"),
        "footer": read_text(template_root / "footer.html"),
    }
    rendered: Dict[str, bytes] = {}
    for public_path in sorted(public_root.rglob("*")):
        if public_path.is_symlink():
            raise BuildError(f"Public source cannot contain symlinks: {public_path}")
        if public_path.is_file():
            relative_path = public_path.relative_to(public_root).as_posix()
            rendered[relative_path] = public_path.read_bytes()

    def add_output(relative_path: str, content: bytes, source: str) -> None:
        if relative_path in rendered:
            raise BuildError(
                f"Generated output {relative_path} collides with public source {source}"
            )
        rendered[relative_path] = content

    for page in configuration["pages"]:
        output = str(page["output"])
        add_output(
            output,
            render_page(page, configuration, source_root, templates).encode("utf-8"),
            f"site page {output}",
        )

    css_sections = [
        read_text(source_root / str(relative_path)).rstrip() + "\n"
        for relative_path in configuration["styles"]
    ]
    generated_css = (
        "/* Generated by scripts/build_site.py; edit site/styles instead. */\n\n"
        + "\n".join(css_sections)
    )
    add_output(
        "static/css/app.css",
        generated_css.encode("utf-8"),
        "site styles",
    )
    asset_root = source_root / "assets"
    generated_assets: List[str] = []
    if asset_root.is_dir():
        for asset_path in sorted(asset_root.rglob("*")):
            if asset_path.is_file():
                relative_path = asset_path.relative_to(asset_root).as_posix()
                output_path = f"static/{relative_path}"
                add_output(output_path, asset_path.read_bytes(), str(asset_path))
                generated_assets.append(output_path)
    manifest = {
        "_generated_by": ASSET_MANIFEST_OWNER,
        "assets": generated_assets,
        "files": {
            relative_path: hashlib.sha256(content).hexdigest()
            for relative_path, content in sorted(rendered.items())
        },
    }
    add_output(
        ASSET_MANIFEST_OUTPUT,
        json.dumps(
            manifest,
            indent=2,
            sort_keys=True,
        ).encode("utf-8")
        + b"\n",
        "build manifest",
    )
    return rendered


def owned_generated_outputs(output_root: Path) -> set[str]:
    owned: set[str] = set()
    if not output_root.is_dir():
        return owned
    for suffix, marker in GENERATED_OWNERSHIP_MARKERS.items():
        for output_path in output_root.rglob(f"*{suffix}"):
            if not output_path.is_file():
                continue
            try:
                with output_path.open("rb") as output_file:
                    header = output_file.read(512)
            except OSError:
                continue
            if marker in header:
                owned.add(output_path.relative_to(output_root).as_posix())

    asset_manifest = output_root / ASSET_MANIFEST_OUTPUT
    try:
        manifest = json.loads(asset_manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        manifest = {}
    if (
        isinstance(manifest, dict)
        and manifest.get("_generated_by") == ASSET_MANIFEST_OWNER
    ):
        owned.add(ASSET_MANIFEST_OUTPUT)
        for relative_path in manifest.get("files", {}):
            if not isinstance(relative_path, str):
                continue
            parsed_path = Path(relative_path)
            if parsed_path.is_absolute() or ".." in parsed_path.parts:
                continue
            owned.add(parsed_path.as_posix())
        for relative_path in manifest.get("assets", []):
            if not isinstance(relative_path, str):
                continue
            parsed_path = Path(relative_path)
            if (
                parsed_path.is_absolute()
                or ".." in parsed_path.parts
                or not relative_path.startswith("static/")
            ):
                continue
            owned.add(parsed_path.as_posix())
    return owned


def obsolete_outputs(
    output_root: Path, generated: Mapping[str, bytes]
) -> List[str]:
    return sorted(owned_generated_outputs(output_root).difference(generated))


def stale_outputs(output_root: Path, generated: Mapping[str, bytes]) -> List[str]:
    stale = []
    for relative_path, expected in generated.items():
        output_path = output_root / relative_path
        try:
            actual = output_path.read_bytes()
        except OSError:
            actual = None
        if actual != expected:
            stale.append(relative_path)
    actual_files = {
        path.relative_to(output_root).as_posix()
        for path in output_root.rglob("*")
        if path.is_file()
    }
    return sorted(set(stale) | actual_files.difference(generated))


def write_outputs(output_root: Path, generated: Mapping[str, bytes]) -> None:
    output_root.parent.mkdir(parents=True, exist_ok=True)
    if output_root.exists():
        if output_root.is_symlink() or not output_root.is_dir():
            raise BuildError(f"Build output must be a normal directory: {output_root}")
        if not any(output_root.iterdir()):
            output_root.rmdir()
        else:
            manifest_path = output_root / ASSET_MANIFEST_OUTPUT
            try:
                manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as error:
                raise BuildError(
                    f"Refusing to replace unowned output directory {output_root}: {error}"
                ) from error
            if manifest.get("_generated_by") != ASSET_MANIFEST_OWNER:
                raise BuildError(f"Refusing to replace unowned output directory: {output_root}")
            owned = set(manifest.get("files", {})) | {ASSET_MANIFEST_OUTPUT}
            actual = {
                path.relative_to(output_root).as_posix()
                for path in output_root.rglob("*")
                if path.is_file()
            }
            unexpected = sorted(actual.difference(owned))
            if unexpected:
                raise BuildError(
                    f"Refusing to remove unowned files from {output_root}: "
                    + ", ".join(unexpected)
                )

    staging_directory = Path(
        tempfile.mkdtemp(prefix=f".{output_root.name}.build-", dir=output_root.parent)
    )
    try:
        for relative_path, content in generated.items():
            output_path = staging_directory / relative_path
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_bytes(content)
        if output_root.exists():
            shutil.rmtree(output_root)
        staging_directory.replace(output_root)
    finally:
        if staging_directory.exists():
            shutil.rmtree(staging_directory)


def parse_arguments(arguments: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build tracked public HTML and CSS from site sources."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero instead of writing when generated output is stale.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT,
        help="Generated site root (default: repository dist/).",
    )
    parser.add_argument(
        "--source-root",
        type=Path,
        default=DEFAULT_SOURCE_ROOT,
        help="Template source root (default: repository site/).",
    )
    parser.add_argument(
        "--public-root",
        type=Path,
        default=DEFAULT_PUBLIC_ROOT,
        help="Static public inputs (default: repository public/).",
    )
    return parser.parse_args(arguments)


def main(arguments: Iterable[str] | None = None) -> int:
    options = parse_arguments(arguments if arguments is not None else sys.argv[1:])
    try:
        generated = generated_files(
            options.source_root.resolve(), options.public_root.resolve()
        )
    except BuildError as error:
        print(f"Site build failed: {error}", file=sys.stderr)
        return 2

    output_root = options.output_root.resolve()
    stale = stale_outputs(output_root, generated)
    if options.check:
        if stale:
            print("Generated output is stale:", file=sys.stderr)
            for relative_path in stale:
                print(f"  {relative_path}", file=sys.stderr)
            print("Run: npm run build:site", file=sys.stderr)
            return 1
        print(f"Generated site is current ({len(generated)} files).")
        return 0

    write_outputs(output_root, generated)
    print(f"Generated {len(generated)} files in {output_root}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
