'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const output=process.env.REVIEW_OUTPUT;if(!output)throw Error('Set REVIEW_OUTPUT to a review artifact directory.');let base=process.env.REVIEW_BASE_URL,server;
const collection={kind:'oglcnac-collections',schema_version:1,collections:[{id:'visual-example',name:'Nuclear proteins',accessions:['P12270','P18583','O15294'],updated:'2026-09-30T12:00:00Z'}]};
const cases=[{name:'search',url:'/atlas/search/?q=OGT&field=gene_name',target:'#atlas-results-heading'}, {name:'filters',url:'/atlas/search/?q=P18583&field=accession&method=ms&year=2020',target:'#atlas-filter-disclosure'}, {name:'batch',url:'/atlas/search/?ids=P12270,P18583,O15294,P12270,MISSING',target:'#atlas-batch-report'}, {name:'selection',url:'/atlas/search/?ids=P12270,P18583,O15294',target:'#atlas-selection-bar'}, {name:'collections',url:'/atlas/collections/',target:'#collection-content'}, {name:'compare',url:'/atlas/compare/?ids=P12270,P18583,O15294',target:'#comparison-grid'}, {name:'compare-four',url:'/atlas/compare/?ids=P12270,O15294,Q6UN15-1,MISSING',target:'#comparison-grid'}, {name:'compare-unavailable',url:'/atlas/compare/?ids=P12270,Q6UN15-1',target:'[data-accession="Q6UN15-1"]'}, {name:'compare-missing',url:'/atlas/compare/?ids=P12270,MISSING',target:'[data-accession=MISSING]'}, {name:'review-decision',url:'/atlas/review/?id=A0A0C4DFX4&site=2416',target:'#review-decision'}, {name:'queue',url:'/atlas/review/',target:'#review-queue'}, {name:'review',url:'/atlas/review/?id=A0A0C4DFX4&site=2416',target:'#review-case'}, {name:'review-history',url:'/atlas/review/?id=P49792&site=868',target:'#review-history'}];
(async()=>{if(!base){const http=require('node:http'),root=process.env.SITE_STATIC_ROOT||path.join(__dirname,'../dist-public');server=http.createServer(async(req,res)=>{let file=path.join(root,new URL(req.url,'http://localhost').pathname);if(!path.extname(file))file=path.join(file,'index.html');try{const body=await fs.readFile(file);res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(body);}catch(_){res.writeHead(404).end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;}
await fs.mkdir(output,{recursive:true});const browser=await chromium.launch();const captures=[];
try{for(const width of [320,390,768,1440,1920])for(const item of cases){const context=await browser.newContext({viewport:{width,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(data=>localStorage.setItem('oglcnac:collections:v1',JSON.stringify(data)),collection);await page.goto(base+item.url);await page.addStyleTag({content:'html {scroll-behavior:auto !important;}'});
 if(item.url.includes('/search/')){await page.waitForSelector('#atlas-selection-bar:not([hidden])');if(item.name==='filters')await page.locator('#atlas-filter-disclosure').evaluate(n=>n.open=true);if(item.name==='batch')await page.locator('#atlas-batch-report').evaluate(n=>n.open=true);if(item.name==='selection'){await page.locator('#atlas-select-matching').click();await page.locator('.atlas-save-disclosure').evaluate(n=>n.open=true);await page.getByLabel('Save to collection',{exact:true}).selectOption('visual-example');}}
 else if(item.name==='collections')await page.waitForFunction(()=>OglcnacTables.get('collection_table').totalRows===3);
 else if(item.url.includes('/compare/'))await page.waitForSelector('#comparison-grid[data-ready=true]');
 else if(item.name==='queue')await page.waitForFunction(()=>OglcnacTables.get('review_table').totalRows===1046);
 else{await page.waitForFunction(()=>!document.getElementById('review-save').disabled);if(['review','review-decision'].includes(item.name)){await page.selectOption('#review-decision-value','propose-correction');await page.fill('#review-coordinate','2239');}else{await page.fill('#reviewer-name','Example curator');await page.fill('#review-rationale','Example local review: supplementary evidence needs verification.');await page.locator('#review-save').click();}}
 await page.locator(item.target).evaluate(n=>n.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForTimeout(100);
 const geometry=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,controls:[...document.querySelectorAll('.atlas-tools-page button,.atlas-tools-page select,.atlas-tools-page input:not([type=checkbox]),.atlas-selection-bar button,.atlas-save-controls input,.atlas-save-controls select,.atlas-filter-fields select')].filter(n=>n.getClientRects().length).map(n=>({id:n.id,text:n.textContent.slice(0,60),left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right,height:n.getBoundingClientRect().height}))}));assert.ok(geometry.scrollWidth<=width,`${item.name} page overflow at ${width}`);assert.deepEqual(errors,[]);assert.ok(geometry.controls.every(n=>n.height>=43&&n.left>=-1&&n.right<=width+1),`${item.name} undersized or clipped controls at ${width}: `+JSON.stringify(geometry.controls.filter(n=>n.height<43||n.left< -1||n.right>width+1)));
 const filename=`${width}-${item.name}.png`;await page.screenshot({path:path.join(output,filename)});captures.push({width,case:item.name,filename,geometry,errors});console.log(filename);await context.close();}}
 finally{await browser.close();if(server)await new Promise(resolve=>server.close(resolve));}await fs.writeFile(path.join(output,'review.json'),JSON.stringify({base,created:new Date().toISOString(),captures},null,2)+'\n');})();
