'use strict';
const fs=require('node:fs'); const crypto=require('node:crypto');
const path=require('node:path'); const http=require('node:http'); const zlib=require('node:zlib');
const {chromium}=require(path.join(process.cwd(),'node_modules/playwright'));
const OUTPUT=process.env.PERF_OUTPUT_ROOT; const SITE_ROOT=process.env.PERF_SITE_ROOT; fs.mkdirSync(OUTPUT,{recursive:true});
const MIME={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.wasm':'application/wasm'};
const server=http.createServer((req,res)=>{let target=path.join(SITE_ROOT,decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!path.extname(target))target=path.join(target,'index.html');try{const body=fs.readFileSync(target);const compressed=zlib.gzipSync(body,{level:6});res.writeHead(200,{'Content-Type':MIME[path.extname(target)]||'application/octet-stream','Content-Encoding':'gzip','Cache-Control':'no-store','Content-Length':compressed.length});res.end(compressed);}catch(e){res.writeHead(404);res.end('Not found');}});
const routes=['/atlas/search/?q=OGT&field=gene_name','/atlas/compare/?ids=P12270,P18583,O15294','/atlas/review/?id=A0A0C4DFX4&site=2416'];
(async()=>{
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true});
const output={createdAt:new Date().toISOString(),base:`http://127.0.0.1:${server.address().port}`,type:'lab measurement, not field Core Web Vitals',conditions:{browser:'Chromium',viewport:{width:390,height:844},deviceScaleFactor:1,cache:'fresh browser context and CDP cache disabled for each run',downloadBytesPerSecond:200000,uploadBytesPerSecond:75000,latencyMs:150,cpuSlowdown:4,timeoutMs:60000},runs:[]};
for(const route of routes){for(let run=1;run<=3;run++){
 const context=await browser.newContext({viewport:output.conditions.viewport,deviceScaleFactor:1});const page=await context.newPage();const session=await context.newCDPSession(page);
 await session.send('Network.enable');await session.send('Network.setCacheDisabled',{cacheDisabled:true});await session.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:75000,connectionType:'cellular4g'});await session.send('Emulation.setCPUThrottlingRate',{rate:4});
 await page.addInitScript(()=>{window.labMetrics={lcp:0,cls:0,shifts:[],longTasks:[],dataReadyAt:null,sequenceReadyAt:null};new PerformanceObserver(l=>l.getEntries().forEach(e=>window.labMetrics.lcp=e.startTime)).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(l=>l.getEntries().forEach(e=>{if(!e.hadRecentInput){window.labMetrics.cls+=e.value;window.labMetrics.shifts.push({time:e.startTime,value:e.value,sources:e.sources.map(s=>({node:s.node?.id||s.node?.tagName,previous:s.previousRect,current:s.currentRect}))});}})).observe({type:'layout-shift',buffered:true});new PerformanceObserver(l=>l.getEntries().forEach(e=>window.labMetrics.longTasks.push({start:e.startTime,duration:e.duration}))).observe({type:'longtask',buffered:true});const timer=setInterval(()=>{const path=location.pathname;const ready=(path==='/atlas/browse/'||path==='/atlas/search/')?window.OglcnacTables?.get('search_result')&&!window.OglcnacTables.get('search_result').loading: path==='/atlas/compare/'?document.querySelector('#comparison-grid[data-ready="true"]'):path==='/atlas/review/'?document.getElementById('review-save')&&!document.getElementById('review-save').disabled:false;if(ready&&window.labMetrics.dataReadyAt===null)window.labMetrics.dataReadyAt=performance.now();const sequence=document.querySelector('#protein-sequence');if(path==='/atlas/detail/'&&ready&&sequence&&!sequence.textContent.includes('Loading')){window.labMetrics.sequenceReadyAt=performance.now();clearInterval(timer)}else if(ready&&path!=='/atlas/detail/')clearInterval(timer)},25);});
 let timer;const result={route,run};const start=Date.now();
 try{await Promise.race([(async()=>{await page.goto(output.base+route,{waitUntil:'domcontentloaded',timeout:60000});if(route.includes('/atlas/'))await page.waitForFunction(()=>window.labMetrics.dataReadyAt!==null,null,{timeout:60000});else await page.waitForLoadState('load',{timeout:60000});await page.waitForTimeout(500);await page.waitForLoadState('networkidle',{timeout:60000});return true})(),new Promise((_,reject)=>timer=setTimeout(()=>reject(new Error('60 second route cap')),60000))]);result.status='complete';}catch(e){result.status='incomplete';result.error=e.message}
 clearTimeout(timer);result.wallMs=Date.now()-start;
 try{Object.assign(result,await page.evaluate(()=>{const resources=performance.getEntriesByType('resource').map(e=>({url:new URL(e.name).pathname,initiator:e.initiatorType,transferBytes:e.transferSize,encodedBytes:e.encodedBodySize,decodedBytes:e.decodedBodySize,startMs:e.startTime,durationMs:e.duration}));const n=performance.getEntriesByType('navigation')[0];return {...window.labMetrics,observedAtMs:performance.now(),navigation:{transferBytes:n?.transferSize,encodedBytes:n?.encodedBodySize,decodedBytes:n?.decodedBodySize,domContentLoadedMs:n?.domContentLoadedEventEnd,loadMs:n?.loadEventEnd,ttfbMs:n?.responseStart},resources,resourceCount:resources.length,totalTransferBytes:resources.reduce((a,x)=>a+x.transferBytes,0)+(n?.transferSize||0),totalEncodedBytes:resources.reduce((a,x)=>a+x.encodedBytes,0)+(n?.encodedBodySize||0),totalDecodedBytes:resources.reduce((a,x)=>a+x.decodedBytes,0)+(n?.decodedBodySize||0)}}));result.longTaskCount=result.longTasks.length;result.longTaskTotalMs=result.longTasks.reduce((s,e)=>s+e.duration,0);result.totalBlockingTimeMs=result.longTasks.reduce((s,e)=>s+Math.max(0,e.duration-50),0);}catch(e){result.metricsError=e.message}
 output.runs.push(result);fs.writeFileSync(path.join(OUTPUT,'results.json'),JSON.stringify(output,null,2));console.log(JSON.stringify({route,run,status:result.status,wallMs:result.wallMs,lcpMs:result.lcp,cls:result.cls,readyMs:result.dataReadyAt,sequenceReadyMs:result.sequenceReadyAt,transferBytes:result.totalTransferBytes,longTaskCount:result.longTaskCount,totalBlockingTimeMs:result.totalBlockingTimeMs}));await context.close();
}}
await browser.close(); await new Promise(resolve=>server.close(resolve));
const median=values=>{const sorted=values.filter(v=>typeof v==='number').sort((a,b)=>a-b);return sorted.length?sorted[Math.floor(sorted.length/2)]:null};
output.metricNotes=[
 'Controlled local lab measurements, not field Core Web Vitals. Same Chromium/390px/1.6Mbps/150ms/CPU4x/cache-disabled conditions as production baseline; local server uses standard HTTP gzip level6. CDN/origin latency beyond configured150ms differs from production.',
 'totalBlockingTimeMs is sum(max(duration-50,0)) over observed long tasks, not Lighthouse TBT.',
 'Readiness includes populated search tables, completed comparison metadata, or the enabled curator decision form with source evidence.',
 'All source data remains unchanged. Dataset indexes/buckets derive deterministically; UI/CSS includes final reviewed loading geometry and visual polish fixes.',
 'Search loads a compact full-corpus projection; comparison and review load only the required accession buckets and local annotations.'
];
output.summary=routes.map(route=>{const runs=output.runs.filter(r=>r.route===route);const row={route,completedRuns:runs.filter(r=>r.status==='complete').length,medianLcpMs:median(runs.map(r=>r.lcp)),medianCls:median(runs.map(r=>r.cls)),medianTransferBytes:median(runs.map(r=>r.totalTransferBytes)),medianDataReadyMs:median(runs.map(r=>r.dataReadyAt)),medianSequenceReadyMs:median(runs.map(r=>r.sequenceReadyAt)),medianObservedBlockingMs:median(runs.map(r=>r.totalBlockingTimeMs)),maxCls:Math.max(...runs.map(r=>r.cls)),maxDataReadyMs:Math.max(...runs.map(r=>r.dataReadyAt||0)),maxTransferBytes:Math.max(...runs.map(r=>r.totalTransferBytes))};row.passes=row.completedRuns===3&&row.medianLcpMs<=2500&&row.maxCls<=0.1&&row.maxDataReadyMs<=8000;return row});
const assets=new Set(routes.map(route=>new URL(route,'http://localhost').pathname.replace(/^\//,'')+'index.html'));
for(const run of output.runs)for(const resource of run.resources||[])assets.add(resource.url.replace(/^\//,''));
output.builtAssets={};for(const asset of [...assets].sort()){const filename=path.join(SITE_ROOT,asset);if(fs.existsSync(filename))output.builtAssets[asset]=crypto.createHash('sha256').update(fs.readFileSync(filename)).digest('hex')}
output.completedAt=new Date().toISOString();
fs.writeFileSync(path.join(OUTPUT,'results.json'),JSON.stringify(output,null,2)+'\n');
fs.writeFileSync(path.join(OUTPUT,'summary.json'),JSON.stringify(output.summary,null,2)+'\n');
process.exitCode=output.summary.every(row=>row.passes)?0:1;
})();
